
Import('*')

libraryName = 'mrjson'
sourceFiles = Split("""
                       mrjson.c
                       yajl/src/yajl.c
                       yajl/src/yajl_alloc.c
                       yajl/src/yajl_buf.c
                       yajl/src/yajl_encode.c
                       yajl/src/yajl_gen.c
                       yajl/src/yajl_lex.c
                       yajl/src/yajl_parser.c
                       yajl/src/yajl_tree.c
                       yajl/src/yajl_version.c
                    """)

cppPath = ['#/source', '#', '#/lib/mrjson', '#/lib/mrjson/yajl-hacks/']

shelbySimpleLibrary(libraryName, sourceFiles, cppPath, defaultDebugEnv, defaultOptEnv)

