sourceFiles = Split("""
                       mrbson.c
                    """)

Import('env')
mrbsonEnv = env.Clone()

mrbsonEnv.MergeFlags('-std=gnu99 -O6 -Wall -Werror -DMONGO_HAVE_UNISTD -static')
mrbsonEnv['CPPPATH'] = ['#/source', '#', '#/lib/mrbson']

mrbson = mrbsonEnv.Library(target = 'mrbson', source = sourceFiles)

mrbsonEnv.Default(mrbson)
