sourceFiles = Split("""
                       mrbson.c
                    """)

Import('env')
mrbsonEnv = env.Clone()

mrbsonEnv.MergeFlags('-O6 -pthread -Wall -Werror -DMONGO_HAVE_UNISTD -static')
mrbsonEnv['CXXFLAGS'] = ['-std=c++0x'] # works around bug in scons MergeFlags, fixed in later versions of scons
mrbsonEnv['CPPPATH'] = ['#/source', '#', '#/lib/mrbson']

mrbson = mrbsonEnv.Library(target = 'mrbson', source = sourceFiles)

mrbsonEnv.Default(mrbson)
