
Import('*')

libraryName = 'mrbson'
sourceFiles = Split("""
                       mrbson.c
                    """)

cppPath = ['#/source', '#', '#/lib/mrbson']

shelbySimpleLibrary(libraryName, sourceFiles, cppPath, defaultDebugEnv, defaultOptEnv)

