env = Environment().Clone()
Export('env')

if GetOption("clean"):

   env.Default('.')
   Clean('.', [ ".sconsign.dblite", ".sconf_temp", "config.log", "build", "bin" ])

else:

   SConscript('source/dashboardIndex/SConscript', variant_dir='build/dashboardIndex/', duplicate=0)

   # libs 
   SConscript('lib/mrjson/SConscript', variant_dir='build/mrjson/', duplicate=0)
   SConscript('lib/mrbson/SConscript', variant_dir='build/mrbson/', duplicate=0)
   SConscript('lib/shelby/SConscript', variant_dir='build/shelby/', duplicate=0)

   # Straight Git submodule - easy since they use scons
   SConscript('lib/mongo-c-driver/SConstruct', variant_dir='build/mongo-c-driver/', duplicate=0)
