
Import('*')

libraryName = 'cvector'
sourceFiles = Split("""
                       cvector.c
                    """)

cppPath = ['#/source', '#', '#/lib/cvector']

shelbySimpleLibrary(libraryName, sourceFiles, cppPath, defaultDebugEnv, defaultOptEnv)

