sourceFiles = Split("""
                       sob.cpp
                    """)

Import('env')
shelbyEnv = env.Clone()

shelbyEnv.MergeFlags('-O6 -pthread -Wall -Werror -DMONGO_HAVE_UNISTD -static')
shelbyEnv['CXXFLAGS'] = ['-std=c++0x'] # works around bug in scons MergeFlags, fixed in later versions of scons
shelbyEnv['CPPPATH'] = ['#/source', '#']

shelby = shelbyEnv.Library(target = 'shelby', source = sourceFiles)

shelbyEnv.Default(shelby)
