sourceFiles = Split("""
                       sob.c
                    """)

Import('env')
shelbyEnv = env.Clone()

shelbyEnv.MergeFlags('-std=gnu99 -O6 -Wall -Werror -DMONGO_HAVE_UNISTD -static')
shelbyEnv['CPPPATH'] = ['#/source', '#']

shelby = shelbyEnv.Library(target = 'shelby', source = sourceFiles)

shelbyEnv.Default(shelby)
