defaults: &defaults
  api_url : "http://audrey2.data.shelby.tv"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production
