defaults: &defaults
  api_url : "http://198.101.158.13"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

arnold:
  <<: *production