defaults: &defaults
  available: false
  tubes:
    websocket_deliver_to_client: "ws_deliver_to_client_gt"
    twitter_backfill: "tw_backfill"
    twitter_add_stream: "tw_stream_add"
    link_processing: "link_processing_gt"
    link_processing_high: "link_processing_high_gt"
    facebook_add_user: "fb_add_user"
    tumblr_add_user: "tumblr_add_user"

development:
  <<: *defaults

test:
  <<: *defaults
  url: 'host:port'
  host: 'host'
  port: 'port'

production: &production
  <<: *defaults
  available: true
  url: '10.181.132.217:11300'
  host: '10.181.132.217'
  port: '11300'

staging:
  <<: *production

arnold:
  <<: *production