defaults: &defaults
  available: false
  tubes:
    websocket_deliver_to_client: "ws_deliver_to_client"
    twitter_backfill: "tw_backfill"
    twitter_add_stream: "tw_stream_add"
    link_processing: "link_processing"
    link_processing_high: "link_processing_high"
    facebook_add_user: "fb_add_user"
    tumblr_add_user: "tumblr_add_user"
    event_tube: "event_tube"
  
development:
  <<: *defaults

test:
  <<: *defaults
  url: 'host:port'
  host: 'host'
  port: 'port'

production:
  <<: *defaults
  available: true
  url: '10.181.132.217:11300'
  host: '10.181.132.217'
  port: '11300'