defaults: &defaults
  api_username : "onshelby"
  api_key : "R_41aac83f2cc30229bded13d2864827d6"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production