defaults: &defaults
  log_file : "log/c_extensions"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production