defaults: &defaults
  multivariate_tests: [
    {
      name: "retention1.0",
      # NB: Changing the details of a bucket will NOT update clients that have already been placed in this bucket (on iOS)
      # Should consider creating new buckets when making significant changes.
      buckets: [
        { 
          name: "A",
          description: "Thursday Evening, Copy v1",
          active: true,
          day: 5,
          time: 1900,
          message: "Yes! Video from %@, %@, %@, and more!"
        },
        {
          name: "B",
          description: "Thursday Evening, Copy v2",
          active: true,
          day: 5,
          time: 1900,
          message: "You've got a bunch of interesting video waiting for you!"
        },
        {
          name: "C",
          description: "Sunday Morning, Copy v1",
          active: true,
          day: 1,
          time: 1000,
          message: "Yes! Video from %@, %@, %@, and more!"
        },
        {
          name: "D",
          description: "Sunday Morning, Copy v2",
          active: true,
          day: 1,
          time: 1000,
          message: "You've got a bunch of interesting video waiting for you!"
        }
      ]
    }
  ]

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

arnold:
  <<: *production
