defaults: &defaults
  multivariate_tests: [
    {
      name: "retention1.0",
      # NB: Changing the details of a bucket will NOT update clients that have already been placed in this bucket (on iOS)
      # Should consider creating new buckets when making important/significant changes.
      buckets: [
        {
          name: "A",
          description: "Thursday Afternoon, Copy v1",
          active: true,
          day: 5,
          time: 1612,
          message: "%@, %@, and %@ shared videos with you.  Nice!"
        },
        {
          name: "B",
          description: "Thursday Afternoon, Copy v2",
          active: true,
          day: 5,
          time: 1612,
          message: "It's Thursday, check out video while you check out from work. ;-)"
        },
        {
          name: "C",
          description: "Sunday Morning, Copy v1",
          active: true,
          day: 1,
          time: 0958,
          message: "%@, %@, and %@ shared videos with you.  Awesome!"
        },
        {
          name: "D",
          description: "Sunday Morning, Copy v2",
          active: true,
          day: 1,
          time: 0958,
          message: "Sunday morning Shelby!  Better than mowing the lawn."
        }
      ]
    }
  ]

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

arnold:
  <<: *production
