defaults: &defaults
  multivariate_tests: [
    {
      name: "retention1.0",
      # NB: Changing the details of a bucket will NOT update clients that have already been placed in this bucket (on iOS)
      # Should consider creating new buckets when making important/significant changes.
      buckets: [
        {
          name: "A",
          description: "Thursday Evening, Copy v1",
          active: false,
          day: 5,
          time: 1900,
          message: "Yes! Video from %@, %@, %@, and more!"
        },
        {
          name: "B",
          description: "Thursday Evening, Copy v2",
          active: false,
          day: 5,
          time: 1900,
          message: "You've got a bunch of interesting video waiting for you!"
        },
        {
          name: "C",
          description: "Sunday Morning, Copy v1",
          active: false,
          day: 1,
          time: 1000,
          message: "Yes! Video from %@, %@, %@, and more!"
        },
        {
          name: "D",
          description: "Sunday Morning, Copy v2",
          active: false,
          day: 1,
          time: 1000,
          message: "You've got a bunch of interesting video waiting for you!"
        },
        {
          name: "E",
          description: "Thursday 509pm / copy1",
          active: false,
          day: 5,
          time: 1709,
          message: "%@ and %@ shared interesting videos. Not sure about %@..."
        },
        {
          name: "F",
          description: "Thursday 509pm / copy2",
          active: false,
          day: 5,
          time: 1709,
          message: "It's Thursday night.  Watch Shelby while your shows DVR!"
        },
        {
          name: "G",
          description: "Friday 1010am / copy1",
          active: true,
          day: 6,
          time: 1010,
          message: "%@ and %@ shared interesting videos! Not sure about %@..."
        },
        {
          name: "H",
          description: "Friday 1010am / copy2",
          active: true,
          day: 6,
          time: 1010,
          message: "It's Friday!  Watch Shelby and get ready for the weekend!"
        }
      ]
    }
  ]

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

arnold:
  <<: *production
