defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: true

development:
  <<: *defaults
  db_name: 'dev-gt-conversation'

test:
  <<: *defaults
  db_name: 'test-gt-conversation'
  mm_use_identity_map: false

production: &production
  <<: *defaults
  db_name: 'gt-conversation'
  db_hosts: ["10.176.69.208:27017", "10.176.69.210:27017"]
  db_replSetName: 'gtConversation'
  db_username: "gt_user"
  db_password: "GT/us3r!!!"

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production
  mm_use_identity_map: false
  db_options:
   :read: :primary