defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: false

development:
  <<: *defaults
  db_name: 'dev-gt-deeplink_cache'

test:
  <<: *defaults
  db_name: 'test-gt-deeplink_cache'

#erm not sure how to set this up
production: &production
  <<: *defaults
  db_name: 'gt-deeplink_cache'
  db_hosts: ["10.183.66.100:27017", "10.183.66.108:27017"]
  db_replSetName: 'gtDeeplinkCache'
  db_username: "gt_user"
  db_password: "GT/us3r!!!"

staging:
  <<: *production

arnold:
  <<: *production
