defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}

development:
  <<: *defaults
  db_name: 'dev-gt-deeplink'

test:
  <<: *defaults
  db_name: 'test-gt-deeplink'

#erm not sure how to set this up
production: &production
  <<: *defaults
  db_name: 'gt-deeplink'
  db_hosts: ["10.176.69.184:27017", "10.176.69.187:27017"]
  db_replSetName: 'gtDeeplink'
  db_username: "gt_user"
  db_password: "GT/us3r!!!"
  
arnold:
  <<: *production
  db_options:
   :read: :primary
