defaults: &defaults
  web_url_base: "http://gt.shelby.tv"
  shelby_logo: "http://api.gt.shelby.tv/shelby.png"
  preferences_link: "http://gt.shelby.tv/preferences"
  # Sharing
  share_frame:
    category: "Share Frame"
    subject: "%{sharers_name} has shared a video with you"
    private_roll_invite_subject: "%{inviters_name} invites you to private roll '%{roll_title}'"
  # Notifications
  notification_sender: "notifications@shelby.tv"
  comment_notification:
    category: "Comment Notifications"
    subject: "the video you shared received a comment!"
  upvote_notification:
    category: "Comment Notifications"
    subject: "the video you shared received an upvote!"
  reroll_notification:
    category: "Reroll Notifications"
    subject: "the video you shared was re-rolled!"
  join_roll_notification:
    category: "Join Roll Notifications"
    subject: "%{users_name} joined the %{roll_description} you started!"
  # GtInterest
  gt_interest_autoresponse:
    category: "Submit GT Interest"
    subject: "Your request for Shelby GT has been received!"
    from: "Shelby GT <contact+gt@shelby.tv>"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  
arnold:
  <<: *production
