defaults: &defaults
  default_rolling_comment: 'Rolled via email'
  email_hook_domain: 'onshelby.tv'
  email_user_keys: {
      roll : 'roll'
  }
  max_rolled_videos: 2

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

arnold:
  <<: *defaults