defaults: &defaults
  share_frame:
    category: "Share Frame"
    subject: "watch this video"
  comment_notification:
    category: "Comment Notifications"
    subject: "the video you shared received a comment!"
  upvote_notification:
    category: "Comment Notifications"
    subject: "the video you shared received an upvote!"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  
arnold:
  <<: *production
