defaults: &defaults
  shelby_address: "110 E 23rd, 10th Floor, New York NY 10010"
  shelby_logo: "http://api.shelby.tv/assets/email_logo.png"
  shelby_logo_gt: "http://shelby.tv/images/assets/shelby_logo.png"
  shelby_tagline: "The perfect stream of videos built for you and powered by your friends."
  preferences_link: "http://shelby.tv/preferences"
  web_url_base: "http://shelby.tv"
  #CSS UI Constants
  font_family      : "'Helvetica Neue',Helvetica,sans-serif"
  font_size        : "13px"
  font_weight      : "normal"
  ui_white         : "#ffffff"
  ui_off_white     : "#f4f4f4"
  ui_black         : "#333333"
  ui_soft_black    : "#555555"
  ui_gray          : "#f1f1f1"
  ui_green         : "#6fbe47"
  ui_red           : "#ee4c4c"
  ui_blue          : "#0590c4"
  ui_facebook_blue : "#013e80"
  ui_twitter_blue  : "#2CAAE1"
  ui_tumblr_blue   : "#2f445b"
  # Sharing
  share_frame:
    category: "Share Frame"
    subject: "%{sharers_name} found a video to share with you"
  # Notifications
  notification_sender: "notifications@shelby.tv"
  comment_notification:
    category: "Comment Notifications"
    subject_a: "%{commenters_name} commented on a video you rolled"
    subject_b: "%{commenters_name} commented on a video on Shelby.tv"
  upvote_notification:
    category: "Heart Notifications"
    subject: "%{upvoters_name} liked your video"
  reroll_notification:
    category: "Share Notifications"
    subject: "%{re_rollers_name} shared your video on Shelby.tv"
  like_notification:
    category: "Like Notifications"
    subject: "%{likers_name} liked a video you shared on Shelby.tv"
    second_lines:
      any_liker: [ "Is this the beginning of a great relationship?",
                   "You were always the popular one, weren't you?",
                   "Pat yourself on the back. You've got good taste."
                 ]
      anonymous: [ "How's it feel to have a secret admirer?" ]
  join_roll_notification:
    category: "Follow Notifications"
    subject: "%{users_name} is following you on Shelby.tv!"
  invite_accepted_notification:
    category: "Invite Accepted Notifications"
    subject: "%{users_name} accepted your invitation to join Shelby.tv"
  # GtInterest
  gt_interest_autoresponse:
    category: "Submit GT Interest"
    subject: "your invite request"
    from: "reece <reece@shelby.tv>"
    reply_to: "contact@shelby.tv"
  beta_invite:
    initial:
      category: "Initial Beta Invite"
      subject: "%{inviters_name} invites you to join Shelby.tv"
      from: "Shelby Invite <contact+invite@shelby.tv>"
  new_user_summary:
    category: "Admin"
    subject: "[%{date}] %{new_users} New Users Yesterday"
    from: "Shelby GT <contact+gt@shelby.tv>"
  # Disucssion Rolls
  discussion_roll:
    category: "Discussion Roll Notifications"
    from_email: "noreply@shelby.tv"
    max_element_count: 9
  # Stats
  weekly_curator_stats:
    category: "Weekly Curator Stats"
    subject: "%{curators_name}, check out your Shelby stats"


development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

arnold:
  <<: *production
