defaults: &defaults
  shelby_address: "110 E 23rd, 10th Floor, New York NY 10010"
  shelby_logo: "http://api.gt.shelby.tv/shelby.png"
  shelby_logo_gt: "http://gt.shelby.tv/images/assets/shelby_logo.png"
  shelby_tagline: "An amazing way to discover and enjoy videos."
  preferences_link: "http://gt.shelby.tv/preferences"
  web_url_base: "http://gt.shelby.tv"
  # Sharing
  share_frame:
    category: "Share Frame"
    subject: "%{sharers_name} has shared a video with you"
    private_roll_invite_subject: "%{inviters_name} invites you to private roll '%{roll_title}'"
  # Notifications
  notification_sender: "notifications@shelby.tv"
  comment_notification:
    category: "Comment Notifications"
    subject: "%{commenters_name} commented on your video"
  upvote_notification:
    category: "Comment Notifications"
    subject: "%{upvoters_name} liked your video"
  reroll_notification:
    category: "Reroll Notifications"
    subject: "%{re_rollers_name} rolled your video"
  join_roll_notification:
    category: "Join Roll Notifications"
    subject: "%{users_name} joined your roll!"
  # GtInterest
  gt_interest_autoresponse:
    category: "Submit GT Interest"
    subject: "Your request for Shelby GT has been received!"
    from: "Shelby GT <contact+gt@shelby.tv>"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  
arnold:
  <<: *production
