defaults: &defaults
  title: Shelby.tv
  #TODO: this should be in Settings::Sailthru 
  sailthru_user_list: 'users'
  
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

arnold:
  <<: *production