defaults: &defaults
  title: "Shelby.tv"
  domain: "shelby.tv"
  api_host: "api.shelby.tv"
  web_host: "shelby.tv"
  override_em_next_tick: false

development:
  <<: *defaults
  api_host: "localhost.shelby.tv:3000"

test:
  <<: *defaults
  override_em_next_tick: true

production: &production
  <<: *defaults

staging:
  <<: *production

arnold:
  <<: *production
  override_em_next_tick: true