defaults: &defaults
  web_account_id: "UA-21191360-6"
  ios_account_id: "UA-21191360-12"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production
  web_account_id: "UA-21191360-8"

email:
  <<: *production

arnold:
  <<: *production