defaults: &defaults
  id: "259310947930.apps.googleusercontent.com"
  secret: "QJJTX5YTX+07rQqdfwCZu5+I"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production