defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: false

development:
  <<: *defaults
  db_name: 'dev-gt-gt-interest'

test:
  <<: *defaults
  db_name: 'test-gt-gt-interest'

production: &production
  <<: *defaults
  db_name: 'gt-gt-interest'
  #db_hosts: ["10.181.135.130:27018", "10.180.131.101:27018"]
  db_hosts: ["nos-db-s0-a:27018", "nos-db-s0-b:27018"]

staging:
  <<: *production

arnold:
  <<: *production
  db_options:
   :read: :primary
