defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}

development:
  <<: *defaults
  db_name: 'dev-gt-gt-interest'

test:
  <<: *defaults
  db_name: 'test-gt-gt-interest'

production: &production
  <<: *defaults
  db_name: 'gt-gt-interest'
  db_hosts: ["10.181.135.130:27018", "10.180.131.101:27018", "10.181.131.114:27018"]

arnold:
  <<: *production
  db_options:
   :read: :primary