defaults: &defaults
  api_key: '9b8c2d291a85a66412fc8c0085125194646fd7a6'
  metric:
    send_invite: 'Send Shelby invitation'
    accept_invite: 'Accept Shelby invitation'
    roll_frame:
      bookmarklet: 'Roll frame via bookmarklet'
      email:
        single: 'Roll single frame via email'
        multiple: 'Roll multiple frames via email'
      extension: 'Roll frame via extension'
    hooks:
      email_invalid_address: 'Sent rolling email from invalid address'
      email_valid_address: 'Sent rolling email from valid address'
    send_email:
      weekly_rec_email: "Sent weekly recommendation email"
    open_email:
      weekly_rec_email: "Opened+weekly+recommendation+email"
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

arnold:
  <<: *production
