defaults: &defaults
  db_options:
   :pool_size: 1

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  db_options:
   :pool_size: 5
  
arnold:
  <<: *production
  db_options:
   :pool_size: 5