defaults: &defaults
  db_options:
   :pool_size: 1
   :w: 0

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  db_options:
   :pool_size: 5

staging:
  <<: *production

arnold:
  <<: *production
  db_options:
   :pool_size: 5