defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: false

development:
  <<: *defaults
  db_name: 'dev-gt-oauth_server'

test:
  <<: *defaults
  db_name: 'test-gt-oauth_server'

#erm not sure how to set this up
production: &production
  <<: *defaults
  db_name: 'gt-oauth_server'
  db_hosts: ["10.181.135.130:27018", "10.181.131.101:27018", "10.181.131.114:27018"]

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production