defaults: &defaults
  access_key_id: "AKIAJSMOE5P3PQHPYOOQ"
  secret_access_key: "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"

development:
  <<: *defaults
  user_avatar_bucket: "dev-shelby-gt-user-avatars"
  roll_images_bucket: "dev-shelby-gt-roll-images"

test:
  <<: *defaults
  user_avatar_bucket: "test-shelby-gt-user-avatars"
  roll_images_bucket: "test-shelby-gt-roll-images"

production: &production
  <<: *defaults
  user_avatar_bucket: "shelby-gt-user-avatars"
  roll_images_bucket: "shelby-gt-roll-images"

staging:
  <<: *production

arnold:
  <<: *production

