defaults: &defaults
  validate_uniqueness_user_nickname: true
  validate_uniqueness_video_provider_name_id: true

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  
arnold:
  <<: *production
  validate_uniqueness_user_nickname: false
  validate_uniqueness_video_provider_name_id: false
