defaults: &defaults
  follow_notification:
    alert: "%{followers_name} is following you on Shelby.tv"
  like_notification:
    alert: "%{likers_name} liked your video on Shelby.tv"
  reroll_notification:
    alert: "%{re_rollers_name} shared your video on Shelby.tv"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production