defaults: &defaults
  follow_notification:
    alert: "%{followers_name} is following you"
  like_notification:
    alert: "%{likers_name} liked your video"
  reroll_notification:
    alert: "%{re_rollers_name} shared your video"
  certificate_file: "certificates/iOS/NightlyProd.pem"
  houston_client_environment_method: :development

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  certificate_file: "certificates/iOS/LiveProd.pem"
  houston_client_environment_method: :production

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production