defaults: &defaults
  video_graph: {
    entries_to_scan : 10,
    min_score : 40.0
  }
  triggered_ios_recs: {
    mortar_recs_weight : 0.7
  }
  people: {
    min_followed_roll_frames : 2
  }

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

arnold:
  <<: *production
