defaults: &defaults
  resque_web_username: "resque"
  resque_web_password: "overtime"
  redis_host: "localhost"
  redis_port: "6379"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  redis_host: "gt-api-b"
  redis_port: "6379"

staging:
  <<: *defaults

email:
  <<: *defaults

arnold:
  <<: *defaults