defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: true

development:
  <<: *defaults
  db_name: 'dev-gt-roll-frame'

test:
  <<: *defaults
  db_name: 'test-gt-roll-frame'

production: &production
  <<: *defaults
  db_name: 'gt-roll-frame'
  db_hosts: ["10.176.69.215:27017", "10.176.69.216:27017"]
  db_replSetName: 'gtRollFrame'
  db_username: "gt_user"
  db_password: "GT/us3r!!!"
  
arnold:
  <<: *production
  mm_use_identity_map: false
  db_options:
   :read: :primary
