defaults: &defaults
  username: "smtp_login@shelby.tv"
  password: "$h3lby"

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production