defaults: &defaults
  allow_origin: "http://web.gt.shelby.tv"
  cross_site_key: "GoatsFTW"
  
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  
arnold:
  <<: *production