defaults: &defaults
  web_domain: "shelby.tv"
  web_root: "http://shelby.tv"
  web_root_secure: "https://shelby.tv"

development:
  <<: *defaults
  web_root: "http://localhost.shelby.tv:3000"

test:
  <<: *defaults

production: &production
  <<: *defaults

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production