defaults: &defaults  
  web_domain: "shelby.tv"
  web_root: "http://shelby.tv"
  
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  
arnold:
  <<: *production