defaults: &defaults
  api:
    dashboard:
      index: 'api.gt.dashboard.index'
      update: 'api.gt.dashboard.update'
    user:
      show: 'api.gt.user.show'
      update: 'api.gt.user.update'
      rolls: 'api.gt.user.rolls'
    roll:
      show: 'api.gt.roll.show'
      share: 'api.gt.roll.share'
      create: 'api.gt.roll.create'
      join: 'api.gt.roll.join'
      leave: 'api.gt.roll.leave'
      update: 'api.gt.roll.update'
      delete: 'api.gt.roll.destroy'
    frame:
      index: 'api.gt.frame.index'
      show: 'api.gt.frame.show'
      create: 'api.gt.frame.create'
      upvote: 'api.gt.frame.upvote'
      add_to_watch_later: 'api.gt.frame.add_to_wl'
      watched: 'api.gt.frame.watched'
      destroy: 'api.gt.frame.destroy'
    conversation:
      show: 'api.gt.conversation.show'
    messages:
      create: 'api.gt.messages.create'
      destroy: 'api.gt.messages.destroy'
    video:
      show: 'api.gt.video.show'
  
  
  # api.gt prefix added in stats manager
  user:
    new:
      faux: "user.new.faux"
      real: "user.new.real"
      converted: "user.new.converted"
      error: "user.new.error"
    signin:
      success:
        twitter: "user.signin.success.twitter"
        facebook: "user.signin.success.facebook"
      failure: "user.signin.failure"
    signout:
      signout: "signout"
    add_service:
      twitter: "user.add_service.twitter"
      facebook: "user.add_service.facebook"
      tumblr: "user.add_service.tumblr"
      error: "user.add_service.error"
    remove_service:
      twitter: "user.remove_service.twitter"
      facebook: "user.remove_service.facebook"
      tumblr: "user.remove_service.tumblr"
      error: "user.add_service.error"
  
  frame:
    watch: "frame.watch"
    share:
      twitter: "frame.share.twitter"
      facebook: "frame.share.facebook"
      tumblr: "frame.share.tumblr"
      email: "frame.share.email"
    upvote: "frame.upvote"
    watch_later: "frame.watch_later"
    re_roll: "frame.re_roll"
    create:
      bookmarklet: "frame.create.bookmarklet"
      extension: "frame.create.extension"
      webapp: "frame.create.webapp"
  
  roll:
    create:
      public: "roll.create.public"
      private: "roll.create.private"
    share:
      twitter: "roll.share.twitter"
      facebook: "roll.share.facebook"
      tumblr: "roll.share.tumblr"
      email: "roll.share.email"
    join: "roll.join"
    leave: "roll.leave"
  
  message:
    create: "message.create"
    delete: "message.delete"
  
  facebook:
    opengraph:
      watch: "facebook.opengraph.watch"
      roll: "facebook.opengraph.roll"
      upvote: "facebook.opengraph.upvote"
  
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

arnold:
  <<: *production