defaults: &defaults
  # api.VER.gt.web prefix added in StatsManager  
  api:
    dashboard:
      index: 'dashboard.index'
      update: 'dashboard.update'
    user:
      show: 'user.show'
      update: 'user.update'
      rolls: 'user.rolls'
    roll:
      show: 'roll.show'
      share: 'roll.share'
      create: 'roll.create'
      join: 'roll.join'
      leave: 'roll.leave'
      update: 'roll.update'
      destroy: 'roll.destroy'
      genius:
        create: "roll.genius.create"
    frame:
      index: 'frame.index'
      show: 'frame.show'
      create: 'frame.create'
      upvote: 'frame.upvote'
      add_to_watch_later: 'frame.add_to_wl'
      watched: 'frame.watched'
      destroy: 'frame.destroy'
      share: 'frame.share'
    conversation:
      show: 'conversation.show'
      index: 'conversation.index'
    messages:
      create: 'messages.create'
      destroy: 'messages.destroy'
    video:
      show: 'video.show'
      find: 'video.find'
  
  user:
    new:
      faux: "user.new.faux"
      real: "user.new.real"
      converted: "user.new.converted"
      error: "user.new.error"
    signin:
      success:
        twitter: "user.signin.success.twitter"
        facebook: "user.signin.success.facebook"
        token: "user.signin.success.token"
      failure: "user.signin.failure"
    signout: "signout"
    add_service:
      twitter: "user.add_service.twitter"
      facebook: "user.add_service.facebook"
      tumblr: "user.add_service.tumblr"
      error: "user.add_service.error"
    remove_service:
      twitter: "user.remove_service.twitter"
      facebook: "user.remove_service.facebook"
      tumblr: "user.remove_service.tumblr"
      error: "user.add_service.error"
  
  frame:
    watch: "frame.watch"
    share:
      twitter: "frame.share.twitter"
      facebook: "frame.share.facebook"
      tumblr: "frame.share.tumblr"
      email: "frame.share.email"
    upvote: "frame.upvote"
    watch_later: "frame.watch_later"
    re_roll: "frame.re_roll"
    create:
      bookmarklet: "frame.create.bookmarklet"
      extension: "frame.create.extension"
      webapp: "frame.create.webapp"
  
  roll:
    create:
      public: "roll.create.public"
      private: "roll.create.private"
    share:
      twitter: "roll.share.twitter"
      facebook: "roll.share.facebook"
      tumblr: "roll.share.tumblr"
      email: "roll.share.email"
    join: "roll.join"
    leave: "roll.leave"
  
  message:
    create: "message.create"
    delete: "message.delete"
  
  facebook:
    opengraph:
      watch: "facebook.opengraph.watch"
      roll: "facebook.opengraph.roll"
      upvote: "facebook.opengraph.upvote"
  
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults

arnold:
  <<: *production
