defaults: &defaults
  key: "mrw08LmNseqVVIa6i8nO5UEl78fxXOGcaSe978iZyrswS2a8Wj"
  secret: "mefqdRTB2eNlTE5EnS3U8Raa5oMKFvo3Llhj2yyTAPGqu2Go90"
  should_send_to_tumblr: false
  
development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  should_send_to_tumblr: false # need an iframe player before we can post!
  
arnold:
  <<: *production