defaults: &defaults
  consumer_key: 5DNrVZpdIwhQthCJJXCfnQ
  consumer_secret: Tlb35nblFFTZRidpu36Uo3z9mfcvSVv1MuZZ19SHaU
  dev_poller_tweets_per_page: 200
  dev_poller_last_page: 17
  should_send_tweet: false
  dummy_twitter_avatar_image_url: "http://dummy.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png"
  user_lookup_batch_size: 100
  user_lookup_max_requests_per_oauth: 150
  twitter_avatar_url_regex: !ruby/regexp '/https?:\/\/[^.]+[.]twimg[.]com\/profile_images\/[^\/]+\/[^\/]+[.][^\/]{2,}/i'
  twitter_default_avatar_url_regex: !ruby/regexp '/https?:\/\/[^.]+[.]twimg[.]com\/sticky\/default_profile_images\/[^\/]+[.][^\/]{2,}/i'

development:
  <<: *defaults
  dev_poller_last_page: 1
  dev_poller_tweets_per_page: 20

test:
  <<: *defaults

production: &production
  <<: *defaults
  should_send_tweet: true

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production