defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}

development:
  <<: *defaults
  db_name: 'dev-gt-user'
  #db_name: 'nos-development'

test:
  <<: *defaults
  db_name: 'test-gt-user'

production:
  <<: *defaults
  db_name: 'gt-user'
  db_host: '108.166.111.208'
  db_port: '27017'
  #db_hosts: ["10.181.135.130:27018", "10.180.131.101:27018", "10.181.131.114:27018"]
  #db_username: "someun"
  #db_password: "somepw"