defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: true
  current_cohort: "post_onboarding"

development:
  <<: *defaults
  db_name: 'dev-gt-user'
  #db_name: 'nos-development'

test:
  <<: *defaults
  db_name: 'test-gt-user'

production: &production
  <<: *defaults
  db_name: 'nos-production'
  db_hosts: ["nos-db-s0-a:27018", "nos-db-s0-b:27018"]

staging:
  <<: *production

email:
  <<: *defaults
  db_name: 'nos-production'
  db_host: 'nos-db-s0-e'
  db_port: '27018'
  db_options:
    :slave_ok: true

arnold:
  <<: *production
  mm_use_identity_map: false
  db_options:
   :read: :primary
   #timing issues when creating new (faux) Users require that Arnold read from primary for User