defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}

development:
  <<: *defaults
  db_name: 'dev-gt-video'

test:
  <<: *defaults
  db_name: 'test-gt-video'

production: &production
  <<: *defaults
  db_name: 'gt-video'
  db_host: '108.166.111.208'
  db_port: '27017'
  #db_hosts: ["host:port", "host:port"]
  db_username: "gt_user"
  db_password: "GT/us3r!!!"
  
arnold:
  <<: *production
  db_options: {:read => :primary}