defaults: &defaults
  domain: 'localhost:3000'

development:
  <<: *defaults

test:
  <<: *defaults

production: &production
  <<: *defaults
  domain: 'api.gt.shelby.tv'

staging:
  <<: *production

email:
  <<: *production

arnold:
  <<: *production