defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: true

development:
  <<: *defaults
  db_name: 'dev-gt-video'

test:
  <<: *defaults
  db_name: 'test-gt-video'

production: &production
  <<: *defaults
  db_name: 'gt-video'
  db_hosts: ["10.176.69.184:27017", "10.176.69.187:27017"]
  db_replSetName: 'gtVideo'
  db_username: "gt_user"
  db_password: "GT/us3r!!!"

staging:
  <<: *production

arnold:
  <<: *production
  mm_use_identity_map: false
  db_options:
   :read: :primary
