defaults: &defaults
  db_host: '127.0.0.1'
  db_port: '27017'
  db_options: {}
  mm_use_identity_map: true
  bucket_size: 50

development:
  <<: *defaults
  db_name: 'dev-gt-video-liker'

test:
  <<: *defaults
  db_name: 'test-gt-video-liker'

production: &production
  <<: *defaults
  db_name: 'gt-video-liker'
  db_hosts: ["10.176.74.214:27017", "10.176.74.228:27017"]
  db_replSetName: 'gtUserAction'
  db_username: "gt_user"
  db_password: "GT/us3r!!!"

staging:
  <<: *production

arnold:
  <<: *production
  mm_use_identity_map: false
  db_options:
   :read: :primary